######################################################################
# Automatically generated by qmake (2.01a) Fri Jun 22 02:00:36 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
